# Generated by Django 4.0.1 on 2023-06-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0004_remove_restaurant_cuisines_restaurant_cuisines'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuisine',
        ),
    ]
