# Generated by Django 4.0.1 on 2023-06-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0005_delete_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(choices=[('Hyderabad', 'Hyderabad'), ('banglore', 'banglore'), ('channai', 'channai'), ('Delhi', 'Delhi'), ('mumbai', 'mumbai')], default='Hyderabad', max_length=100),
        ),
    ]
